### ISSUE TITLE
Error  initInitialise: Can't lock /var/run/pigpio.pid

### ISSUE THREAD

**Issue by ajjsss** [nkolban/jpigpio#19]
Getting error "Can't lock /var/run/pigpio.pid" when attempting to run Blink_Test as shown below:

pi@raspberrypi:~ $ sudo java -Djava.library.path=/home/pi -jar Desktop/Test_Blink.jar
Test_Blink
2017-12-05 11:36:46 initInitialise: Can't lock /var/run/pigpio.pid
jpigpio.PigpioException: (-1) pigpio initialisation failed
	at jpigpio.Pigpio.gpioInitialize(Native Method)
	at tests.Test_Blink.run(Test_Blink.java:43)
	at tests.Test_Blink.main(Test_Blink.java:30)

**Comment by a-weinert** [comment]
I have exactly the same problem with the linked (non socket) variant.
Additionally, the socket variant would run but do nothing at all with I/O.
Note: On the same Raspi C-control programmes using the installed pigpiod daemon work flawlessly.
Note 2: Its a 3b with headless Stretch. I just use the git cloned library
 -    03.05.2019  19:24           206.623 libJPigpioC.so

More help / documentation would be fine.
Thanks a lot in advance
Albrecht

**Comment by w4mmp** [comment]
Hello 
I have the same problem with a very basic test program:
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <unistd.h>
#include <time.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <fcntl.h>

#include "pigpio.h"


int main (int argc,char **argv){

if (gpioInitialise() < 0){
        printf("pigs init failed\n");
        }
else{
        printf("pigs init success\n");
}
}


The output of this program is:
ron@multus-sdr:~/src/si/pigs $ sudo ./pigtest
2020-03-03 12:38:49 initInitialise: Can't lock /var/run/pigpio.pid
pigs init failed

This is on a RPi 4B running Raspbian (Buster).

Thanks,
Ron

Is there
